### ISSUE TITLE
Could you please provide an example for Gradle?

### ISSUE THREAD

**Issue by SetoKaiba** [38leinaD/quarkus-native-app-starter#1]
Could you please provide an example for Gradle?
I'm developing with Windows. But I don't have enough memory for docker or vm to build native image . I'd like to try GitHub Actions.

**Comment by 38leinaD** [comment]
Please see this project for examples using gradle: https://github.com/38leinaD/bpmn-diff

**Comment by SetoKaiba** [comment]
Thank you. I've finally make my own. But for my case, I have to chmod 777 gradlew. Because my project is developed in Windows. And also, I use the ./gradlew build -x test -Dquarkus.package.type=native
